version: "3.3"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
  
  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
  
  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile