version: "3.3"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
  
  ml-prod:
    build:
      context: ./indexer
      dockerfile: Dockerfile
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile