version: "3.3"
services:

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend-dev:
    ports:
      - "3000:3000"
    volumes:
      - ./backend/app:/app
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile

volumes:
  app-db-data: