"""Add user id to query model

Revision ID: 07d1a223c231
Revises: f52fb6fac039
Create Date: 2021-11-09 01:27:30.180230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07d1a223c231'
down_revision = 'f52fb6fac039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('user', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'user')
    # ### end Alembic commands ###
