"""add last updated and last cursor fields to google token table

Revision ID: 117d0741d9fc
Revises: b83fed527553
Create Date: 2022-03-13 02:38:00.105190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '117d0741d9fc'
down_revision = 'b83fed527553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('googletoken', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('googletoken', sa.Column('last_cursor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('googletoken', 'last_cursor')
    op.drop_column('googletoken', 'time_updated')
    # ### end Alembic commands ###
