"""make word position nullable

Revision ID: 12734a7d2915
Revises: d76900a04ef1
Create Date: 2021-11-17 01:57:57.885741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12734a7d2915'
down_revision = 'd76900a04ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'word_positions',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'word_positions',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
