"""Add extra field to integration table

Revision ID: 495cbf71c777
Revises: 2caa4330704d
Create Date: 2022-04-26 19:17:33.857197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '495cbf71c777'
down_revision = '2caa4330704d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('extra', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'extra')
    # ### end Alembic commands ###
