"""Add last cursor field to notion integration

Revision ID: 7d6050d15a27
Revises: e416fe541b87
Create Date: 2022-03-07 04:40:01.671225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d6050d15a27'
down_revision = 'e416fe541b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notiontoken', sa.Column('last_cursor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notiontoken', 'last_cursor')
    # ### end Alembic commands ###
