"""add temp encrypted token column

Revision ID: 8e901c11c62f
Revises: 1109ceebae67
Create Date: 2021-12-20 05:29:59.454752

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e901c11c62f'
down_revision = '1109ceebae67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notiontoken', sa.Column('encrypted_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
    op.alter_column('notiontoken', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notiontoken', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notiontoken', 'encrypted_token')
    # ### end Alembic commands ###
