"""Add vector count to document model

Revision ID: 9a7e92a7a9e1
Revises: f8a11de6c79b
Create Date: 2022-01-03 02:08:42.713671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a7e92a7a9e1'
down_revision = 'f8a11de6c79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('num_vectors', sa.Integer(), nullable=True))
    op.alter_column('document', 'embeddings',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'embeddings',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('document', 'num_vectors')
    # ### end Alembic commands ###
