"""Added name to document table

Revision ID: b2582556db22
Revises: bdc40d6b066a
Create Date: 2021-11-03 18:20:18.906544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2582556db22'
down_revision = 'bdc40d6b066a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'name')
    # ### end Alembic commands ###
