"""add last updated field to notion token

Revision ID: b83fed527553
Revises: 7d6050d15a27
Create Date: 2022-03-07 16:59:44.027568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b83fed527553'
down_revision = '7d6050d15a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notiontoken', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notiontoken', 'time_updated')
    # ### end Alembic commands ###
