"""Add team name to logged users

Revision ID: d76900a04ef1
Revises: 65d9dcc5a142
Create Date: 2021-11-15 01:23:15.768902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd76900a04ef1'
down_revision = '65d9dcc5a142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loggeduser', sa.Column('team_name', sa.String(), nullable=True))
    op.add_column('loggeduser', sa.Column('team_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loggeduser', 'team_id')
    op.drop_column('loggeduser', 'team_name')
    # ### end Alembic commands ###
