"""modify query table

Revision ID: d8b5f14016ff
Revises: 9a7e92a7a9e1
Create Date: 2022-02-10 02:26:12.320256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8b5f14016ff'
down_revision = '9a7e92a7a9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('query_id', sa.String(), nullable=True))
    op.add_column('query', sa.Column('channel', sa.String(), nullable=True))
    op.drop_column('query', 'text')
    op.drop_column('query', 'embedding')
    op.drop_column('query', 'evidence')
    op.drop_column('query', 'result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('result', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('query', sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('query', sa.Column('embedding', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('query', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('query', 'channel')
    op.drop_column('query', 'query_id')
    # ### end Alembic commands ###
