"""add voters field

Revision ID: e416fe541b87
Revises: 771732fe6781
Create Date: 2022-03-02 00:22:50.191092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e416fe541b87'
down_revision = '771732fe6781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('voters', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'voters')
    # ### end Alembic commands ###
