"""Added google token table

Revision ID: e7db041c5299
Revises: 0741840910eb
Create Date: 2021-12-24 23:15:04.450638

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7db041c5299'
down_revision = '0741840910eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('googletoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('encrypted_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_googletoken_id'), 'googletoken', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_googletoken_id'), table_name='googletoken')
    op.drop_table('googletoken')
    # ### end Alembic commands ###
