"""Add users field to document table

Revision ID: efaf115c6266
Revises: d8b5f14016ff
Create Date: 2022-02-17 04:29:09.890177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efaf115c6266'
down_revision = 'd8b5f14016ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('users', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('document', 'user',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'user',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('document', 'users')
    # ### end Alembic commands ###
