"""Add user and file id to document

Revision ID: f52fb6fac039
Revises: 99c0d29b3e76
Create Date: 2021-11-09 00:53:53.835916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f52fb6fac039'
down_revision = '99c0d29b3e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('user', sa.String(), nullable=False))
    op.add_column('document', sa.Column('file_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'file_id')
    op.drop_column('document', 'user')
    # ### end Alembic commands ###
