"""Add channel id to tokens

Revision ID: f8a11de6c79b
Revises: daa164fc1d32
Create Date: 2021-12-30 03:42:27.191586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8a11de6c79b'
down_revision = 'daa164fc1d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('googletoken', sa.Column('channel_id', sa.String(), nullable=True))
    op.add_column('notiontoken', sa.Column('channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notiontoken', 'channel_id')
    op.drop_column('googletoken', 'channel_id')
    # ### end Alembic commands ###
